packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.2.6
  '@prisma/adapter-pg': 6.18.0
  '@prisma/client': ^6.18.0
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slot': ^1.2.3
  '@tailwindcss/postcss': ^4.1.16
  '@tanstack/react-form': ^1.23.8
  '@tanstack/react-query': ^5.90.5
  '@tanstack/react-query-devtools': ^5.90.2
  '@trpc/client': ^11.7.1
  '@trpc/react-query': ^11.7.1
  '@trpc/server': ^11.7.1
  '@trpc/tanstack-react-query': ^11.7.1
  '@types/mdx': ^2.0.13
  '@types/node': ^24.9.1
  '@types/pg': ^8.15.5
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@vercel/analytics': ^1.5.0
  babel-plugin-react-compiler: ^1.0.0
  better-auth: ^1.3.30
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^17.2.3
  fumadocs-core: 16.0.1
  fumadocs-mdx: 13.0.0
  fumadocs-ui: 16.0.1
  hono: ^4.10.3
  lucide-react: ^0.546.0
  next: 16.0.0
  next-themes: ^0.4.6
  nuqs: ^2.7.2
  pg: 8.16.3
  postcss: ^8.5.6
  prisma: ^6.18.0
  react: 19.2.0
  react-dom: 19.2.0
  resend: ^6.3.0
  sonner: ^2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.16
  tsdown: ^0.15.9
  tsx: ^4.20.6
  turbo: ^2.5.8
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  ultracite: 5.6.4
  wrangler: ^4.45.0
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - workerd
