packages:
  - apps/*
  - packages/*

catalog:
  '@prisma/client': ^6.18.0
  better-auth: ^1.3.30
  dotenv: ^17.2.3
  tsdown: ^0.15.9
  typescript: ^5.9.3
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@prisma/engines'
